"""`gdmd spec --card` / `--section` (WS4 build, D-024 §1, D-029, spec §9.4)."""
from __future__ import annotations

import re

import pytest
from click.testing import CliRunner

from game_design_md import spec_cmd
from game_design_md.cli import main

TEXT = spec_cmd.spec_text()
LINES = TEXT.split("\n")
CARD = spec_cmd.card(TEXT)
SECTIONS = spec_cmd.sections(TEXT)
INDEX_RE = re.compile(r"^\s*- (?:§[\d.]+|Appendix [A-Z]) .*`gdmd spec --section ([\w.]+)`$")


def _innermost(line_no: int):
    inside = [s for s in SECTIONS if s.start <= line_no <= s.end]
    return max(inside, key=lambda s: s.level) if inside else None


def test_completeness_every_rfc2119_sentence_is_in_the_card_or_pointed_to():
    """D-024 §1: every line carrying an uppercase RFC-2119 keyword is in the
    card, or inside a section the card lists a `--section` pointer to, and
    that pointer's output contains it."""
    pointed = {m.group(1) for ln in CARD.split("\n") if (m := INDEX_RE.match(ln))}
    card_lines = set(CARD.split("\n"))
    checked = 0
    for i, line in enumerate(LINES, 1):
        kws = spec_cmd.rfc2119_keywords(line)
        if not kws:
            continue
        checked += len(kws)
        if line in card_lines:
            continue
        sec = _innermost(i)
        assert sec is not None, f"line {i} is outside every section and not in the card"
        assert sec.id in pointed, (i, sec.id)
        assert line in spec_cmd.section_text(sec.id, TEXT).split("\n")
    assert checked >= 29          # keywords (27 lines) when the card was built


def test_code_span_mentions_are_not_requirements():
    assert spec_cmd.rfc2119_keywords("the keywords (`MUST`, `SHALL NOT`)") == []
    assert spec_cmd.rfc2119_keywords("Engines MUST honor that order") == ["MUST"]


def test_every_excerpt_is_a_verbatim_slice_of_the_spec():
    """Between the card's own label lines, every run of lines is a contiguous
    slice of the spec."""
    labels = re.compile(r"^(# |## |> Generated by |`\[n MUST\]` counts )")
    runs, cur = [], []
    for ln in CARD.split("\n"):
        if labels.match(ln) or INDEX_RE.match(ln):
            if cur:
                runs.append(cur)
            cur = []
            continue
        cur.append(ln)
    if cur:
        runs.append(cur)
    for run in runs:
        body = "\n".join(run).strip("\n")
        if body:
            for para in body.split("\n\n"):
                assert para in TEXT, para[:80]


def test_index_lists_every_section_once_in_order():
    ids = [m.group(1) for ln in CARD.split("\n") if (m := INDEX_RE.match(ln))]
    assert ids == [s.id for s in SECTIONS]
    assert "5.2" in ids and "9.9.2" in ids and "A" in ids


def test_sections_skip_headings_inside_code_fences():
    titles = [s.title for s in SECTIONS]
    assert "High Concept" not in titles and "Tokens" not in titles
    s52 = next(s for s in SECTIONS if s.id == "5.2")
    assert "## High Concept" in spec_cmd.section_text("5.2", TEXT)
    assert s52.end < next(s for s in SECTIONS if s.id == "6").start


@pytest.mark.parametrize("arg,want", [("4.8", "4.8"), ("§9.9.2", "9.9.2"), ("4.8.", "4.8"),
                                      ("a", "A"), ("Appendix B", "B")])
def test_section_ids(arg, want):
    body = spec_cmd.section_text(arg, TEXT)
    sec = next(s for s in SECTIONS if s.id == want)
    assert body == "\n".join(LINES[sec.start - 1:sec.end])
    assert body.split("\n")[0] == LINES[sec.start - 1]


def test_section_includes_subsections():
    assert "#### 9.9.2 The lowering rule (normative)" in spec_cmd.section_text("9.9", TEXT)


def test_missing_anchor_fails_loudly():
    broken = TEXT.replace("**Namespace ownership.**", "**Namespaces.**")
    with pytest.raises(spec_cmd.CardAnchorMissing, match="Namespace ownership"):
        spec_cmd.card(broken)


def test_card_is_short_and_names_its_source():
    assert len(CARD) < 0.1 * len(TEXT)
    import hashlib
    assert hashlib.sha256(TEXT.encode()).hexdigest()[:12] in CARD.split("\n")[2]


def test_cli():
    r = CliRunner()
    assert r.invoke(main, ["spec", "--card"]).output == CARD
    out = r.invoke(main, ["spec", "--section", "9.9.4"])
    assert out.exit_code == 0 and out.output.startswith("#### 9.9.4 `gdmd graph`")
    bad = r.invoke(main, ["spec", "--section", "99"])
    assert bad.exit_code == 2 and "no section '99'" in bad.output
    assert r.invoke(main, ["spec", "--card", "--section", "3"]).exit_code == 2
    assert r.invoke(main, ["spec"]).output == TEXT


def test_committed_card_matches_the_spec():
    """D-024 adoption (D-025 Rule C PASS): CLAUDE.md imports docs/spec-card.md,
    so the committed card must be exactly `gdmd spec --card` of the current
    spec. Regenerate with `gdmd spec --card > docs/spec-card.md`."""
    from tests.conftest import REPO_ROOT
    assert (REPO_ROOT / "docs/spec-card.md").read_text(encoding="utf-8") == CARD
    claude = (REPO_ROOT / "CLAUDE.md").read_text(encoding="utf-8")
    assert "- Format definition: @docs/spec-card.md" in claude
